### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by rafiq991008** [Drutol/MALClient#125] opened 2017-05-09 19:49 UTC
![image](https://cloud.githubusercontent.com/assets/28575814/25869588/6856d2d6-3533-11e7-8882-9dd56f9c45b1.png)

It's crash when first start after installation. On latest Windows 10 Creators Update, 32 - bit. Acer SW3-013. It also do show the blue loading spin but not visible in the screenshot.

**Comment by Drutol** [comment] 2017-05-09 20:48
Thanks for report!

It happens every time right? I'll be able to check that tomorrow in the afternoon.

**Comment by Drutol** [comment] 2017-05-10 14:01
Hmm, I'm unable to reproduce this issue, do you mind installing debug version of an app so I can diagnose the reason?

**Comment by hohoaisan** [comment] 2017-05-10 15:54
Mobile 149393.1198 has this issue, loading and crash :|

**Comment by hohoaisan** [comment] 2017-05-10 15:55
I mean 14393.1198

**Comment by Drutol** [comment] 2017-05-10 16:35
Hmm, try running this version: https://rink.hockeyapp.net/apps/b79e78858bdf44c4bfc3a1f37c8fd90c/app_versions/131

I should get detailed crash info :)

**Comment by hohoaisan** [comment] 2017-05-10 17:20
That Debug app can't install on my phone. Tried to reintall it from Store... https://postimg.org/image/brvtfgyxf/7c287cbc/

**Comment by Drutol** [comment] 2017-05-10 17:22
It's for desktop only. Desktop is okay for you?

**Comment by hohoaisan** [comment] 2017-05-10 17:37
I have no Desktop right now, maybe RAFIQ991008 will give you answer.

**Comment by rafiq991008** [comment] 2017-05-10 18:54
I'm using tablet PC for running MAL Client. For some reason, turn off tablet mode, start the MALClient app, resize the window size, and let it freeze, till it close itself, then start again MALClient works for me.

**Comment by Drutol** [comment] 2017-05-10 18:57
Hmm, I've never tried it on tablet... nor am I able to :(

Did you try the debug version?

**Comment by Drutol** [comment] 2017-05-10 18:58
@Guerra24 resizing strikes again (#120), could you try this debug version?

**Comment by rafiq991008** [comment] 2017-05-10 18:59
nope, I just try the Store version. maybe I try reinstall for reproducing the issue.

**Comment by Drutol** [comment] 2017-05-10 18:59
When it'll crash on this special version I should be able to tell more about this issue.

**Comment by Guerra24** [comment] 2017-05-10 19:02
Testing now

**Comment by rafiq991008** [comment] 2017-05-10 19:13
I'm using 32-bit Windows, it rejecting the debug version since the package is 64-bit.
![image](https://cloud.githubusercontent.com/assets/28575814/25916604/ceed1662-35f7-11e7-976e-d681158fde96.png)

**Comment by Drutol** [comment] 2017-05-10 19:18
Oh, I won't be able to upload 32bit version today unfortunately :(

**Comment by hohoaisan** [comment] 2017-05-11 00:22
Hey, try Monument Browser, this app has the same issue with MALClient:
+ Can't do anything
+ When i hide the nav bar, they don't respond
I think maybe my phone's current build problem, i'm asking my friend about it.

**Comment by hohoaisan** [comment] 2017-05-11 14:24
I asked my friends and they said MALClient works fine in previous mobile build (14393.1066, may be CU, too), waiing for their report in 14393.1198 :)

**Comment by rafiq991008** [comment] 2017-05-11 14:56
Drutol, I tried with my desktop today, this is what happened

![image](https://cloud.githubusercontent.com/assets/28575814/25955919/094c30fe-369d-11e7-9b33-cbed5d74f3bc.png)

**Comment by Drutol** [comment] 2017-05-11 15:01
Ugh, it looks like crash reporting won't even work with app failing like this...

**Comment by rafiq991008** [comment] 2017-05-11 15:04
ahaha, I've installed your debug version, and the same things happen

**Comment by Drutol** [comment] 2017-05-11 15:06
Can you crash it a few times so that reports get sent, if crash reporting is working properly...?

**Comment by rafiq991008** [comment] 2017-05-11 15:08
I just need to crash it and it'll automatically send the reports to you, right?

**Comment by Drutol** [comment] 2017-05-11 15:11
It should, I've just managed to replicate it on work computer. It just doesn't crash but is frozen forever...

**Comment by rafiq991008** [comment] 2017-05-11 15:14
Sometimes it crash, but most of the time it's frozen with blue circle mouse cursor keep spinning. And that's the issue.

**Comment by rafiq991008** [comment] 2017-05-11 15:45
I think I found kind of solution. Keep open and exit the apps till the "Rate MALClient" appear...
![65498748954653](https://cloud.githubusercontent.com/assets/28575814/25958615/b13139d0-36a3-11e7-8b3d-bc4efda4ccc2.png)

...then everything works fine after that.

![85749814984](https://cloud.githubusercontent.com/assets/28575814/25958614/b1189e20-36a3-11e7-939a-d4c604a43d71.png)

**Comment by Drutol** [comment] 2017-05-11 17:59
I'm really confused now. I'll try to patch it out tomorrow if I find the source of this problem.

**Comment by Drutol** [comment] 2017-05-11 19:19
Clue 1. It crashes at work, doesn't crash on my home workstation.

**Comment by Drutol** [comment] 2017-05-11 19:23
What's your build?
![image](https://cloud.githubusercontent.com/assets/6102530/25967909/02299b48-3690-11e7-9aa3-6908a716cee0.png)

**Comment by rafiq991008** [comment] 2017-05-12 06:34
My build

![image](https://cloud.githubusercontent.com/assets/28575814/25985971/041f5a6a-3720-11e7-870a-eed7c7849ac7.png)

**Comment by Drutol** [comment] 2017-05-12 06:36
I was going to write that I found the solution, but widnows has pranked me...

**Comment by Drutol** [comment] 2017-05-12 07:16
I'm really clueless it sometimes works and sometimes not...

**Comment by Drutol** [comment] 2017-05-12 07:21
I'm considering falling back to Anniversary SDK as it didn't occur there...

**Comment by Guerra24** [comment] 2017-05-12 07:23
I found a way to prevent the crash, following the steps in the video fixed the resizing crash (I don't how). Uploading now...

**Comment by Guerra24** [comment] 2017-05-12 07:32
Forgot to add, the fix only works with the selected tab (watching, on hold, plan to watch, etc), switching to other tab will rollback the fix and doesn't happen in the watching tab.

**Comment by rafiq991008** [comment] 2017-05-12 08:20
Guerra24 mine is not resizing issue, it's the application that freeze, no matter how the screen is, either maximized or windowed. :(

**Comment by hohoaisan** [comment] 2017-05-12 09:37
I don't know why, but MALClient has worked again. Monument Browser with freezing issue had been fixed with an update.

**Comment by Drutol** [comment] 2017-05-12 10:24
That's highly probable that MSFT did something wrong/changed something here.

**Comment by Drutol** [comment] 2017-05-12 10:54
@Guerra24 however I try I'm unable to crash it... https://gifyu.com/image/bTSU

**Comment by Drutol** [comment] 2017-05-12 11:28
Try this version: https://1drv.ms/u/s!Am1xQK-HVf_IlMMFN8FCZHiYjbEnmg
I've randomly made some changes hoping that it will help...

**Comment by Guerra24** [comment] 2017-05-12 19:24
That version doesn't work, it freezes and stays open until I close it.

**Comment by Drutol** [comment] 2017-05-12 19:42
Going back to Anniversary SDK is an only option then...

**Comment by Guerra24** [comment] 2017-05-12 19:46
UPDATE: Rollback to the old version and still doesn't work, I'm going to try with the store version, if that doesn't work means that I can't install any uwp app.

**Comment by Drutol** [comment] 2017-05-12 19:46
I'll upload the same version but with other targeted SDK in a sec.

**Comment by Drutol** [comment] 2017-05-12 19:48
PS: MSFT just broke another crucial thing in the most recent update on Android so I'm a bit let down by MSFT now

**Comment by Guerra24** [comment] 2017-05-12 19:48
What the... It works again. This is soooooo inconsistent, I'm lost.

**Comment by Drutol** [comment] 2017-05-12 19:50
I've debugged when it was behaving this way... *NO* info whatsoever.
On the other hand it never breaks on my home computer.

**Comment by Guerra24** [comment] 2017-05-12 19:53
I'm going to download Visual Studio and debug it, reporting results Sun or Mon

**Comment by Drutol** [comment] 2017-05-12 19:54
Oh, that would be convenient ^^. It should compile&run instantly (I did clean build today on work computer)

**Comment by Drutol** [comment] 2017-05-12 19:58
This one is targeting Anniversary Update:
https://rink.hockeyapp.net/manage/apps/341224/app_versions/132

**Comment by FoxInFlame** [comment] 2017-05-13 09:59
@rafiq991008 Really off topic, but is that AI Kizuna in your wallpaper?

**Comment by Drutol** [comment] 2017-05-13 10:01
Is there any other option? :D

**Comment by rafiq991008** [comment] 2017-05-13 13:32
@FoxInFlame off topic😂😂😂but yeah, Kizuna Ai.

**Comment by FoxInFlame** [comment] 2017-05-13 13:36
@rafiq991008 Could you give me the link for the wallpaper? I need it :)

Also, your system is in Japanese, you speak it?

**Comment by rafiq991008** [comment] 2017-05-13 13:41
@FoxInFlame i screenshot it from YouTube, you should check there. Btw i still study Jap. Malay and English were my native language. Really2 off-topic🤣

**Comment by FoxInFlame** [comment] 2017-05-13 13:45
Thanks! I won't interfere anymore with this issue (keyword *this*😋).

**Comment by Drutol** [comment] 2017-05-13 14:03
Well, offtopic is pretty freqent around here I don't mind it if anyone asks ^^
So many 日本語 "wielders" around...

**Comment by hohoaisan** [comment] 2017-05-13 14:20
Hmmm, just MALClient? will you built another app?

**Comment by Drutol** [comment] 2017-05-13 14:43
I'm not sure I follow you...

**Comment by sesshoth** [comment] 2017-11-03 12:21
Hey Duro, I keep having an issue where the app used to work but I had a windows update and now I can't seem to get the app working. I'm on desktop and the app just won't fully load, it starts up then shuts down.

**Comment by sesshoth** [comment] 2017-11-03 12:44
I have also tried the debug but I keep getting this
![malclient problem](https://user-images.githubusercontent.com/26685991/32374253-3c5ea78c-c073-11e7-89ba-0b41191201c6.jpg)

**Closed** 2018-08-02 05:42 UTC
Labels: Kill me plz, VooDoo
